<?php

require_once '../src/Mail/Address/MobileJp.php';

// phpunit Mail_Address_MobileJpTest Mail_Address_MobileJpTest.php 

/**
 * Test class for Mail_Address_MobileJp.
 * Generated by PHPUnit on 2010-12-28 at 00:31:46.
 */
class Mail_Address_MobileJpTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Mail_Address_MobileJp
     */
    protected $object;

    private $docomo = array(
        'foobar@docomo.ne.jp',
    );

    private $ezweb = array(
        'foobar@ezweb.ne.jp',
    );

    private $softbank = array(
        'foobar@softbank.ne.jp',
        'foobar@disney.ne.jp',
        'foobar@d.vodafone.ne.jp',
    );

    private $other = array(
        'foobar@willcom.com',
    );

    private $notMobile = array(
        'foobar@exmple.com',
        'foobar@docomo.co.jp',
    );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp( ) {
        $this->object = Mail_Address_MobileJp::getInstance( );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown( ) {
    }

    public function testIsMobileJp( ) {
        $emails = array_merge($this->docomo, $this->ezweb, $this->softbank, $this->other);
        foreach ( $emails as $email ) {
            $this->assertTrue( $this->object->isMobileJp( $email ), $email );
        }
        foreach ( $this->notMobile as $email ) {
            $this->assertFalse( $this->object->isMobileJp( $email ), $email );
        }
    }

    public function testIsImode( ) {
        foreach ( $this->docomo as $email ) {
            $this->assertTrue( $this->object->isImode( $email ), $email );
        }

        $emails = array_merge($this->notMobile, $this->ezweb, $this->softbank, $this->other);
        foreach ( $emails as $email ) {
            $this->assertFalse( $this->object->isImode( $email ), $email );
        }
    }

    public function testIsEzweb( ) {
        foreach ( $this->ezweb as $email ) {
            $this->assertTrue( $this->object->isEzweb( $email ), $email );
        }

        $emails = array_merge($this->notMobile, $this->docomo, $this->softbank, $this->other);
        foreach ( $emails as $email ) {
            $this->assertFalse( $this->object->isEzweb( $email ), $email );
        }
    }

    public function testIsSoftbank( ) {
        foreach ( $this->softbank as $email ) {
            $this->assertTrue( $this->object->isSoftbank( $email ), $email );
        }

        $emails = array_merge($this->notMobile, $this->docomo, $this->ezweb, $this->other);
        foreach ( $emails as $email ) {
            $this->assertFalse( $this->object->isSoftbank( $email ), $email );
        }
    }
}
?>
